=== sizious/shenmue-translation-pack/Package/Binary Translator/Common/translation.dtd
<!ELEMENT translation (header, script, allocation_table)>

<!ELEMENT header EMPTY>
<!ATTLIST header
    game CDATA #REQUIRED
    platform CDATA #REQUIRED
    region CDATA #REQUIRED
    addrbase CDATA #REQUIRED
>

<!ELEMENT script (section+, insert*, patch*)>

<!ELEMENT section (translate*) >
<!ATTLIST section
    name CDATA #REQUIRED
>

<!ELEMENT translate (ptr+) >
<!ATTLIST translate
    text CDATA #REQUIRED
>

<!ELEMENT insert (ptr+) >
<!ATTLIST insert
    text CDATA #REQUIRED
>

<!ELEMENT patch (ptr+) >
<!ATTLIST patch
    addr CDATA #REQUIRED
>

<!ELEMENT ptr EMPTY>
<!ATTLIST ptr
    addr CDATA #REQUIRED
>

<!ELEMENT allocation_table (block+) >
<!ELEMENT block EMPTY>
<!ATTLIST block
    addr    CDATA #REQUIRED
    size    CDATA #REQUIRED
>

=== sizious/shenmue-translation-pack/Shenmue Binary Translator/Common/vision_de_ayla/s2paldc.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE translation SYSTEM "translation.dtd">

<translation>

	<!-- Header -->
    <header game="SHENMUE" platform="DC" region="USA" />

	<!-- Dictionnaires des chaines -->
	<script>
        <section name="Options" >

			<translate text="Dialog/Text" >
				<ptr addr="0x237558" />
				<ptr addr="0x2375e8" />
				<ptr addr="0x237678" />
				<ptr addr="0x237708" />
			</translate>

			<translate text="Sound" >
				<ptr addr="0x237560" />
				<ptr addr="0x2375f0" />
				<ptr addr="0x237680" />
				<ptr addr="0x237710" />
			</translate>

			<translate text="Shenmue Mode" >
				<ptr addr="0x237580" />
				<ptr addr="0x237610" />
				<ptr addr="0x2376a0" />
				<ptr addr="0x237730" />
			</translate>

			<translate text="Cinema Mode" >
				<ptr addr="0x237588" />
				<ptr addr="0x237618" />
				<ptr addr="0x2376a8" />
				<ptr addr="0x237738" />
			</translate>

			<translate text="Text Mode" >
				<ptr addr="0x237590" />
				<ptr addr="0x237620" />
				<ptr addr="0x2376b0" />
				<ptr addr="0x237740" />
			</translate>

			<translate text="Game Mode" >
				<ptr addr="0x237598" />
				<ptr addr="0x237628" />
				<ptr addr="0x2376b8" />
				<ptr addr="0x237748" />
			</translate>

			<translate text="Mono" >
				<ptr addr="0x2375a0" />
				<ptr addr="0x237630" />
				<ptr addr="0x2376c0" />
				<ptr addr="0x237750" />
			</translate>

			<translate text="Stereo" >
				<ptr addr="0x2375a8" />
				<ptr addr="0x237638" />
				<ptr addr="0x2376c8" />
				<ptr addr="0x237758" />
			</translate>

			<translate text="On" >
				<ptr addr="0x2375b0" />
				<ptr addr="0x237640" />
				<ptr addr="0x2376d0" />
				<ptr addr="0x237760" />
			</translate>

			<translate text="Off" >
				<ptr addr="0x2375b8" />
				<ptr addr="0x237648" />
				<ptr addr="0x2376d8" />
				<ptr addr="0x237768" />
			</translate>

			<translate text=" Run" >
				<ptr addr="0x2375c0" />
				<ptr addr="0x237650" />
				<ptr addr="0x2376e0" />
				<ptr addr="0x237770" />
			</translate>

			<translate text=" Zoom" >
				<ptr addr="0x2375c8" />
				<ptr addr="0x237658" />
				<ptr addr="0x2376e8" />
				<ptr addr="0x237778" />
			</translate>

			<translate text="Look" >
				<ptr addr="0x2375d0" />
				<ptr addr="0x2376f0" />
				<ptr addr="0x237780" />
				<ptr addr="0x237660" />
			</translate>

			<translate text="Move" >
				<ptr addr="0x2375d8" />
				<ptr addr="0x2376f8" />
				<ptr addr="0x237788" />
				<ptr addr="0x237668" />
			</translate>

			<translate text="Analog" >
				<ptr addr="0x237568" />
				<ptr addr="0x237688" />
				<ptr addr="0x237718" />
				<ptr addr="0x2375f8" />
			</translate>

			<translate text="Thumb Pad" >
				<ptr addr="0x2375e0" />
				<ptr addr="0x237700" />
				<ptr addr="0x237790" />
			</translate>

			<translate text="Toggle" >
				<ptr addr="0x237570" />
				<ptr addr="0x237690" />
				<ptr addr="0x237718" />
				<ptr addr="0x237600" />
			</translate>

			<translate text="Controls" >
				<ptr addr="0x237578" />
				<ptr addr="0x237698" />
				<ptr addr="0x237720" />
			</translate>
        </section>

		<!-- Texte non modifiable -->
		<insert text="DC_KANJI.FON" >
            <ptr addr="0x2cef0" />
        </insert>

		<!-- Pointeurs a mettre a jour -->
		<patch addr="0x21bc54" >
            <ptr addr="0x46acc" />
            <ptr addr="0x46c48" />
            <ptr addr="0x70a70" />
		</patch>
    </script>


	<!-- Indique l'emplacement des blocs liberables pour stocker nos chaines -->
	<allocation_table>
		<block addr="0x2fffff" size="0x657"  />
		<block addr="0x2fffee" size="0x2060" />
		<block addr="0x2fffe2" size="0x1a30"  />
		<block addr="0x21d540" size="0x95"   />
		<block addr="0x220408" size="0x1f96" />
		<block addr="0x2224bc" size="0x1683" />
	</allocation_table> 

</translation>
